language: node_js
node_js:
- 16

services:
- docker

## Pre-testing installs
install:
- echo "nothing needs to be installed"

## Scripts to be run such as tests
before_script:
- echo "no tests. Yes there will be tests"

## Build
script:
- docker --version
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend

## Tagging
- docker tag udagram-api-feed namhaibk105/udagram-api-feed:latest
- docker tag udagram-api-user namhaibk105/udagram-api-user:latest
- docker tag udagram-frontend namhaibk105/udagram-frontend:v4
- docker tag udagram-reverseproxy namhaibk105/udagram-reverseproxy:latest

## Format DOCKER information
after-success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push namhaibk105/udagram-reverseproxy:latest
- docker push namhaibk105/udagram-api-feed:latest
- docker push namhaibk105/udagram-api-user:latest
- docker push namhaibk105/udagram-frontend:v4