apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: IQoJb3JpZ2luX2VjEMz//////////wEaCXVzLXdlc3QtMiJIMEYCIQCFERD0Nf9OyNAqG6ZOLRImM/0mFYX3Z+YzV3ZnQYEF5QIhAMJhbJQw9m4T00huVKiDb5Pp2/rcHiQcrTnpdzjarVQ6Kr4CCEUQAxoMMDc5MjY0NzE1NjkzIgz4sCZSiBxrZkFz2eMqmwLXn/TBxickf9UuWf2Pf0FCMJe9p+eT+Dn9j9hrsQ8mK2D0uYZUsKwZxktQ/9PBJ0NmSp3wdYn4HYlALw6UMeXw8HRnjFT43Xq3Au0e3lAafh0AS+fz4CXGqQjDrw4Cxs94gUcnFagd0Im03vKVLyneBYBIVPwNEu5VQJqYmVONZrkT3nWB/RrlUMpO/mW+meTV12UtSiuKm9EEMra/ZcxhJPOJHawr/+dzWYDPieCWESfD9mpKkhl/l8lBpmdAJ1HZp/Bhd9y/ss94H3/B6IdsIz2+RzmeHno+56dIdQ1V7y5IuVk2zjfEN797j/xYXaRq8jdM/XRtxu5kVsN7wPFh664f4LJ4huEYI6OqcDNrwaM+zQ61bmU2YPcUMMTp/bgGOpwBKXtKDYIJ3AsgS25pFDimhcOnCZdBbIdDTZRwcZnInzgW5qj08pJ9b6WaWK6GospncfE7/SwxOB9E/ZPkvVC+4M0bYHni5rEGeuUlV/wNLfG+NTmpKqI/CGtebfF9f9TM4JI4bCkMmcfv+TG2VlCYvS8W0KZFMm6XgHkWPl5ZjVJpXQRf/1SBbSutL7Th/VuHf1csF67kX2eCZhlx
